as:
  build: ./server/aerospike
  ports:
    - 3000:3000
    - 3001:3001
    - 3002:3002
    - 3003:3003 
  volumes:
  - ./volumes/aerospike/data:/opt/aerospike/data

ofa:
  build: ./server/ofa
  dockerfile: Dockerfile.prod
  ports:
    - 30003:30003
  volumes:
    - ./server/ofa/application/src:/application/src

