FROM node:6.5.0

RUN mkdir /application

WORKDIR /application
ADD ./application/package.json /application/package.json
ADD ./application/nodemon.json /application/nodemon.json

WORKDIR /application
RUN npm install

EXPOSE 30003

CMD NODE_ENV=production npm run start
